// Bundles the viewer (viewer.js + observer-model.js + three.js) into one script and
// writes the standalone page index.html, which works offline and from file://.
//
//   node build-viewer.mjs                         # index.html
//   node build-viewer.mjs --website ../../gratheon.com
//
// With --website it also copies the bundle, CSS and GLB into the gratheon.com
// repo and refreshes the embed block between the entrance-observer markers in
// the Entrance Observer product page.
import { build } from 'esbuild';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const read = (f) => readFileSync(join(here, f), 'utf8');

const result = await build({
  stdin: { contents: "import { mountAll } from './viewer.js';\nmountAll();\n", resolveDir: here, loader: 'js' },
  bundle: true,
  format: 'iife',
  minify: true,
  target: 'es2020',
  write: false,
  legalComments: 'none',
});
const bundle = result.outputFiles[0].text;
const css = read('viewer.css');
const markup = read('viewer.html').trim();

// ---- standalone page ------------------------------------------------------
const page = `<!-- Generated by build-viewer.mjs from viewer.html, viewer.css, viewer.js and observer-model.js. Do not edit. -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Entrance Observer</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
:root { --page-bg: #eef0ec; }
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) { --page-bg: #121512; color-scheme: dark; } }
:root[data-theme="dark"] { --page-bg: #121512; color-scheme: dark; }
html, body { height: 100%; }
body { margin: 0; background: var(--page-bg); font-family: "IBM Plex Sans", system-ui, -apple-system, "Segoe UI", sans-serif; }
.entrance-observer { --eo-height: 100%; border: 0; border-radius: 0; }
${css}
</style>
${markup}
<script>${bundle.replace(/<\/script/gi, '<\\/script')}</script>
`;
writeFileSync(join(here, 'index.html'), page);
console.log(`wrote index.html (${(page.length / 1024).toFixed(0)} KB)`);

// ---- website --------------------------------------------------------------
const i = process.argv.indexOf('--website');
if (i > 0) {
  const site = resolve(process.argv[i + 1]);
  const out = (rel) => {
    const p = join(site, 'content', rel);
    mkdirSync(dirname(p), { recursive: true });
    return p;
  };
  // content/triangle/** is copied verbatim (not concatenated into main.js).
  writeFileSync(out('triangle/entrance-observer/entrance-observer-viewer.js'), bundle);
  writeFileSync(out('assets/css/entrance-observer.css'), css);
  if (existsSync(join(here, 'entrance-observer.glb'))) copyFileSync(join(here, 'entrance-observer.glb'), out('assets/models/entrance-observer.glb'));

  const embed = markup
    .replace(/\s*<header data-eo="header">[\s\S]*?<\/header>/, '')
    .replace('href="entrance-observer.glb"', 'href="/assets/models/entrance-observer.glb" download');
  const block = `<!-- entrance-observer:start (generated by entrance-observer/3d-model/build-viewer.mjs) -->\n${embed}\n<script defer src="/assets/triangle/entrance-observer/entrance-observer-viewer.js"></script>\n<!-- entrance-observer:end -->`;
  const marker = /<!-- entrance-observer:start[\s\S]*?<!-- entrance-observer:end -->/;
  const pages = ['content/products/entrance_observer/entrance_observer.md'];
  for (const rel of pages) {
    const pagePath = join(site, rel);
    const text = readFileSync(pagePath, 'utf8');
    if (!marker.test(text)) throw new Error(`${pagePath} has no <!-- entrance-observer:start --> ... <!-- entrance-observer:end --> block`);
    writeFileSync(pagePath, text.replace(marker, () => block));
  }
  console.log(`updated ${site}: viewer bundle (${(bundle.length / 1024).toFixed(0)} KB), CSS, GLB, ${pages.length} page embeds`);
}
